/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: aulora.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "aulora.pb-c.h"
void   main__location__init
                     (Main__Location         *message)
{
  static const Main__Location init_value = MAIN__LOCATION__INIT;
  *message = init_value;
}
size_t main__location__get_packed_size
                     (const Main__Location *message)
{
  assert(message->base.descriptor == &main__location__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__location__pack
                     (const Main__Location *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__location__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__location__pack_to_buffer
                     (const Main__Location *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__location__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Location *
       main__location__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Location *)
     protobuf_c_message_unpack (&main__location__descriptor,
                                allocator, len, data);
}
void   main__location__free_unpacked
                     (Main__Location *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__location__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__payload__init
                     (Main__Payload         *message)
{
  static const Main__Payload init_value = MAIN__PAYLOAD__INIT;
  *message = init_value;
}
size_t main__payload__get_packed_size
                     (const Main__Payload *message)
{
  assert(message->base.descriptor == &main__payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__payload__pack
                     (const Main__Payload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__payload__pack_to_buffer
                     (const Main__Payload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Payload *
       main__payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Payload *)
     protobuf_c_message_unpack (&main__payload__descriptor,
                                allocator, len, data);
}
void   main__payload__free_unpacked
                     (Main__Payload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__request__init
                     (Main__Request         *message)
{
  static const Main__Request init_value = MAIN__REQUEST__INIT;
  *message = init_value;
}
size_t main__request__get_packed_size
                     (const Main__Request *message)
{
  assert(message->base.descriptor == &main__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__request__pack
                     (const Main__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__request__pack_to_buffer
                     (const Main__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Request *
       main__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Request *)
     protobuf_c_message_unpack (&main__request__descriptor,
                                allocator, len, data);
}
void   main__request__free_unpacked
                     (Main__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__pod__init
                     (Main__Pod         *message)
{
  static const Main__Pod init_value = MAIN__POD__INIT;
  *message = init_value;
}
size_t main__pod__get_packed_size
                     (const Main__Pod *message)
{
  assert(message->base.descriptor == &main__pod__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__pod__pack
                     (const Main__Pod *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__pod__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__pod__pack_to_buffer
                     (const Main__Pod *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__pod__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Pod *
       main__pod__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Pod *)
     protobuf_c_message_unpack (&main__pod__descriptor,
                                allocator, len, data);
}
void   main__pod__free_unpacked
                     (Main__Pod *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__pod__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__data__init
                     (Main__Data         *message)
{
  static const Main__Data init_value = MAIN__DATA__INIT;
  *message = init_value;
}
size_t main__data__get_packed_size
                     (const Main__Data *message)
{
  assert(message->base.descriptor == &main__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__data__pack
                     (const Main__Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__data__pack_to_buffer
                     (const Main__Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Data *
       main__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Data *)
     protobuf_c_message_unpack (&main__data__descriptor,
                                allocator, len, data);
}
void   main__data__free_unpacked
                     (Main__Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__plane__init
                     (Main__Plane         *message)
{
  static const Main__Plane init_value = MAIN__PLANE__INIT;
  *message = init_value;
}
size_t main__plane__get_packed_size
                     (const Main__Plane *message)
{
  assert(message->base.descriptor == &main__plane__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__plane__pack
                     (const Main__Plane *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__plane__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__plane__pack_to_buffer
                     (const Main__Plane *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__plane__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Plane *
       main__plane__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Plane *)
     protobuf_c_message_unpack (&main__plane__descriptor,
                                allocator, len, data);
}
void   main__plane__free_unpacked
                     (Main__Plane *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__plane__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__vessel__init
                     (Main__Vessel         *message)
{
  static const Main__Vessel init_value = MAIN__VESSEL__INIT;
  *message = init_value;
}
size_t main__vessel__get_packed_size
                     (const Main__Vessel *message)
{
  assert(message->base.descriptor == &main__vessel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__vessel__pack
                     (const Main__Vessel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__vessel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__vessel__pack_to_buffer
                     (const Main__Vessel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__vessel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Vessel *
       main__vessel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Vessel *)
     protobuf_c_message_unpack (&main__vessel__descriptor,
                                allocator, len, data);
}
void   main__vessel__free_unpacked
                     (Main__Vessel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__vessel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__vehicle__init
                     (Main__Vehicle         *message)
{
  static const Main__Vehicle init_value = MAIN__VEHICLE__INIT;
  *message = init_value;
}
size_t main__vehicle__get_packed_size
                     (const Main__Vehicle *message)
{
  assert(message->base.descriptor == &main__vehicle__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__vehicle__pack
                     (const Main__Vehicle *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__vehicle__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__vehicle__pack_to_buffer
                     (const Main__Vehicle *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__vehicle__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Vehicle *
       main__vehicle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Vehicle *)
     protobuf_c_message_unpack (&main__vehicle__descriptor,
                                allocator, len, data);
}
void   main__vehicle__free_unpacked
                     (Main__Vehicle *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__vehicle__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__balloon__init
                     (Main__Balloon         *message)
{
  static const Main__Balloon init_value = MAIN__BALLOON__INIT;
  *message = init_value;
}
size_t main__balloon__get_packed_size
                     (const Main__Balloon *message)
{
  assert(message->base.descriptor == &main__balloon__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__balloon__pack
                     (const Main__Balloon *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__balloon__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__balloon__pack_to_buffer
                     (const Main__Balloon *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__balloon__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Balloon *
       main__balloon__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Balloon *)
     protobuf_c_message_unpack (&main__balloon__descriptor,
                                allocator, len, data);
}
void   main__balloon__free_unpacked
                     (Main__Balloon *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__balloon__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__report__init
                     (Main__Report         *message)
{
  static const Main__Report init_value = MAIN__REPORT__INIT;
  *message = init_value;
}
size_t main__report__get_packed_size
                     (const Main__Report *message)
{
  assert(message->base.descriptor == &main__report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__report__pack
                     (const Main__Report *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__report__pack_to_buffer
                     (const Main__Report *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Report *
       main__report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Report *)
     protobuf_c_message_unpack (&main__report__descriptor,
                                allocator, len, data);
}
void   main__report__free_unpacked
                     (Main__Report *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__spacecraft__init
                     (Main__Spacecraft         *message)
{
  static const Main__Spacecraft init_value = MAIN__SPACECRAFT__INIT;
  *message = init_value;
}
size_t main__spacecraft__get_packed_size
                     (const Main__Spacecraft *message)
{
  assert(message->base.descriptor == &main__spacecraft__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__spacecraft__pack
                     (const Main__Spacecraft *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__spacecraft__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__spacecraft__pack_to_buffer
                     (const Main__Spacecraft *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__spacecraft__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Spacecraft *
       main__spacecraft__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Spacecraft *)
     protobuf_c_message_unpack (&main__spacecraft__descriptor,
                                allocator, len, data);
}
void   main__spacecraft__free_unpacked
                     (Main__Spacecraft *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__spacecraft__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__weather__init
                     (Main__Weather         *message)
{
  static const Main__Weather init_value = MAIN__WEATHER__INIT;
  *message = init_value;
}
size_t main__weather__get_packed_size
                     (const Main__Weather *message)
{
  assert(message->base.descriptor == &main__weather__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__weather__pack
                     (const Main__Weather *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__weather__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__weather__pack_to_buffer
                     (const Main__Weather *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__weather__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Weather *
       main__weather__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Weather *)
     protobuf_c_message_unpack (&main__weather__descriptor,
                                allocator, len, data);
}
void   main__weather__free_unpacked
                     (Main__Weather *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__weather__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__message__init
                     (Main__Message         *message)
{
  static const Main__Message init_value = MAIN__MESSAGE__INIT;
  *message = init_value;
}
size_t main__message__get_packed_size
                     (const Main__Message *message)
{
  assert(message->base.descriptor == &main__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__message__pack
                     (const Main__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__message__pack_to_buffer
                     (const Main__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Message *
       main__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Message *)
     protobuf_c_message_unpack (&main__message__descriptor,
                                allocator, len, data);
}
void   main__message__free_unpacked
                     (Main__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__audio__init
                     (Main__Audio         *message)
{
  static const Main__Audio init_value = MAIN__AUDIO__INIT;
  *message = init_value;
}
size_t main__audio__get_packed_size
                     (const Main__Audio *message)
{
  assert(message->base.descriptor == &main__audio__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__audio__pack
                     (const Main__Audio *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__audio__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__audio__pack_to_buffer
                     (const Main__Audio *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__audio__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__Audio *
       main__audio__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__Audio *)
     protobuf_c_message_unpack (&main__audio__descriptor,
                                allocator, len, data);
}
void   main__audio__free_unpacked
                     (Main__Audio *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__audio__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__file__init
                     (Main__File         *message)
{
  static const Main__File init_value = MAIN__FILE__INIT;
  *message = init_value;
}
size_t main__file__get_packed_size
                     (const Main__File *message)
{
  assert(message->base.descriptor == &main__file__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__file__pack
                     (const Main__File *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__file__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__file__pack_to_buffer
                     (const Main__File *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__file__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__File *
       main__file__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__File *)
     protobuf_c_message_unpack (&main__file__descriptor,
                                allocator, len, data);
}
void   main__file__free_unpacked
                     (Main__File *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__file__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor main__location__field_descriptors[3] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Location, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Location, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Location, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__location__field_indices_by_name[] = {
  2,   /* field[2] = altitude */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
};
static const ProtobufCIntRange main__location__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor main__location__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Location",
  "Location",
  "Main__Location",
  "main",
  sizeof(Main__Location),
  3,
  main__location__field_descriptors,
  main__location__field_indices_by_name,
  1,  main__location__number_ranges,
  (ProtobufCMessageInit) main__location__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__payload__field_descriptors[4] =
{
  {
    "chunk",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Payload, chunk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chunks",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Payload, chunks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Main__Payload, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Main__Payload, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__payload__field_indices_by_name[] = {
  0,   /* field[0] = chunk */
  1,   /* field[1] = chunks */
  3,   /* field[3] = data */
  2,   /* field[2] = hash */
};
static const ProtobufCIntRange main__payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor main__payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Payload",
  "Payload",
  "Main__Payload",
  "main",
  sizeof(Main__Payload),
  4,
  main__payload__field_descriptors,
  main__payload__field_indices_by_name,
  1,  main__payload__number_ranges,
  (ProtobufCMessageInit) main__payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__request__field_descriptors[2] =
{
  {
    "chunk",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Request, chunk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Main__Request, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__request__field_indices_by_name[] = {
  0,   /* field[0] = chunk */
  1,   /* field[1] = hash */
};
static const ProtobufCIntRange main__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor main__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Request",
  "Request",
  "Main__Request",
  "main",
  sizeof(Main__Request),
  2,
  main__request__field_descriptors,
  main__request__field_indices_by_name,
  1,  main__request__number_ranges,
  (ProtobufCMessageInit) main__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__pod__field_descriptors[9] =
{
  {
    "sender",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__Pod, sender),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Main__Pod, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__Pod, source),
    &main__location__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destination",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__Pod, destination),
    &main__location__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flight_radius",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Pod, flight_radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "priority",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Pod, priority),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hops",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Pod, hops),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__Pod, payload),
    &main__payload__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__Pod, request),
    &main__request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__pod__field_indices_by_name[] = {
  3,   /* field[3] = destination */
  4,   /* field[4] = flight_radius */
  6,   /* field[6] = hops */
  7,   /* field[7] = payload */
  5,   /* field[5] = priority */
  8,   /* field[8] = request */
  0,   /* field[0] = sender */
  2,   /* field[2] = source */
  1,   /* field[1] = timestamp */
};
static const ProtobufCIntRange main__pod__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor main__pod__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Pod",
  "Pod",
  "Main__Pod",
  "main",
  sizeof(Main__Pod),
  9,
  main__pod__field_descriptors,
  main__pod__field_indices_by_name,
  1,  main__pod__number_ranges,
  (ProtobufCMessageInit) main__pod__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__data__field_descriptors[10] =
{
  {
    "report",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Main__Data, n_report),
    offsetof(Main__Data, report),
    &main__report__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weather",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Main__Data, n_weather),
    offsetof(Main__Data, weather),
    &main__weather__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Main__Data, n_message),
    offsetof(Main__Data, message),
    &main__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Main__Data, n_audio),
    offsetof(Main__Data, audio),
    &main__audio__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Main__Data, n_file),
    offsetof(Main__Data, file),
    &main__file__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "balloon",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__Data, balloon),
    &main__balloon__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plane",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__Data, plane),
    &main__plane__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vessel",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__Data, vessel),
    &main__vessel__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__Data, vehicle),
    &main__vehicle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spacecraft",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__Data, spacecraft),
    &main__spacecraft__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__data__field_indices_by_name[] = {
  3,   /* field[3] = audio */
  5,   /* field[5] = balloon */
  4,   /* field[4] = file */
  2,   /* field[2] = message */
  6,   /* field[6] = plane */
  0,   /* field[0] = report */
  9,   /* field[9] = spacecraft */
  8,   /* field[8] = vehicle */
  7,   /* field[7] = vessel */
  1,   /* field[1] = weather */
};
static const ProtobufCIntRange main__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor main__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Data",
  "Data",
  "Main__Data",
  "main",
  sizeof(Main__Data),
  10,
  main__data__field_descriptors,
  main__data__field_indices_by_name,
  1,  main__data__number_ranges,
  (ProtobufCMessageInit) main__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__plane__field_descriptors[3] =
{
  {
    "wind_speed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Plane, wind_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ground_speed",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Plane, ground_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "squawk",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__Plane, squawk),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__plane__field_indices_by_name[] = {
  1,   /* field[1] = ground_speed */
  2,   /* field[2] = squawk */
  0,   /* field[0] = wind_speed */
};
static const ProtobufCIntRange main__plane__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor main__plane__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Plane",
  "Plane",
  "Main__Plane",
  "main",
  sizeof(Main__Plane),
  3,
  main__plane__field_descriptors,
  main__plane__field_indices_by_name,
  1,  main__plane__number_ranges,
  (ProtobufCMessageInit) main__plane__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__vessel__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__Vessel, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__vessel__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange main__vessel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor main__vessel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Vessel",
  "Vessel",
  "Main__Vessel",
  "main",
  sizeof(Main__Vessel),
  1,
  main__vessel__field_descriptors,
  main__vessel__field_indices_by_name,
  1,  main__vessel__number_ranges,
  (ProtobufCMessageInit) main__vessel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__vehicle__field_descriptors[1] =
{
  {
    "speed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Vehicle, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__vehicle__field_indices_by_name[] = {
  0,   /* field[0] = speed */
};
static const ProtobufCIntRange main__vehicle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor main__vehicle__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Vehicle",
  "Vehicle",
  "Main__Vehicle",
  "main",
  sizeof(Main__Vehicle),
  1,
  main__vehicle__field_descriptors,
  main__vehicle__field_indices_by_name,
  1,  main__vehicle__number_ranges,
  (ProtobufCMessageInit) main__vehicle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__balloon__field_descriptors[1] =
{
  {
    "speed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Balloon, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__balloon__field_indices_by_name[] = {
  0,   /* field[0] = speed */
};
static const ProtobufCIntRange main__balloon__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor main__balloon__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Balloon",
  "Balloon",
  "Main__Balloon",
  "main",
  sizeof(Main__Balloon),
  1,
  main__balloon__field_descriptors,
  main__balloon__field_indices_by_name,
  1,  main__balloon__number_ranges,
  (ProtobufCMessageInit) main__balloon__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__report__field_descriptors[2] =
{
  {
    "subject",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__Report, subject),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__Report, body),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__report__field_indices_by_name[] = {
  1,   /* field[1] = body */
  0,   /* field[0] = subject */
};
static const ProtobufCIntRange main__report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor main__report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Report",
  "Report",
  "Main__Report",
  "main",
  sizeof(Main__Report),
  2,
  main__report__field_descriptors,
  main__report__field_indices_by_name,
  1,  main__report__number_ranges,
  (ProtobufCMessageInit) main__report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__spacecraft__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__Spacecraft, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__spacecraft__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange main__spacecraft__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor main__spacecraft__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Spacecraft",
  "Spacecraft",
  "Main__Spacecraft",
  "main",
  sizeof(Main__Spacecraft),
  1,
  main__spacecraft__field_descriptors,
  main__spacecraft__field_indices_by_name,
  1,  main__spacecraft__number_ranges,
  (ProtobufCMessageInit) main__spacecraft__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__weather__field_descriptors[4] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Main__Weather, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Main__Weather, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Main__Weather, humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pressure",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Main__Weather, pressure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__weather__field_indices_by_name[] = {
  2,   /* field[2] = humidity */
  3,   /* field[3] = pressure */
  1,   /* field[1] = temperature */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange main__weather__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor main__weather__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Weather",
  "Weather",
  "Main__Weather",
  "main",
  sizeof(Main__Weather),
  4,
  main__weather__field_descriptors,
  main__weather__field_indices_by_name,
  1,  main__weather__number_ranges,
  (ProtobufCMessageInit) main__weather__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__message__field_descriptors[3] =
{
  {
    "receiver",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__Message, receiver),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__Message, body),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__Message, location),
    &main__location__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__message__field_indices_by_name[] = {
  1,   /* field[1] = body */
  2,   /* field[2] = location */
  0,   /* field[0] = receiver */
};
static const ProtobufCIntRange main__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor main__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Message",
  "Message",
  "Main__Message",
  "main",
  sizeof(Main__Message),
  3,
  main__message__field_descriptors,
  main__message__field_indices_by_name,
  1,  main__message__number_ranges,
  (ProtobufCMessageInit) main__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__audio__field_descriptors[3] =
{
  {
    "receiver",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__Audio, receiver),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__Audio, duration),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blob",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Main__Audio, blob),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__audio__field_indices_by_name[] = {
  2,   /* field[2] = blob */
  1,   /* field[1] = duration */
  0,   /* field[0] = receiver */
};
static const ProtobufCIntRange main__audio__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor main__audio__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.Audio",
  "Audio",
  "Main__Audio",
  "main",
  sizeof(Main__Audio),
  3,
  main__audio__field_descriptors,
  main__audio__field_indices_by_name,
  1,  main__audio__number_ranges,
  (ProtobufCMessageInit) main__audio__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__file__field_descriptors[3] =
{
  {
    "receiver",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__File, receiver),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__File, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blob",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Main__File, blob),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__file__field_indices_by_name[] = {
  2,   /* field[2] = blob */
  1,   /* field[1] = name */
  0,   /* field[0] = receiver */
};
static const ProtobufCIntRange main__file__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor main__file__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.File",
  "File",
  "Main__File",
  "main",
  sizeof(Main__File),
  3,
  main__file__field_descriptors,
  main__file__field_indices_by_name,
  1,  main__file__number_ranges,
  (ProtobufCMessageInit) main__file__init,
  NULL,NULL,NULL    /* reserved[123] */
};
