// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aulora.proto

package aulora

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Location struct {
	Latitude             uint32   `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            uint32   `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude             uint32   `protobuf:"varint,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() uint32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() uint32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetAltitude() uint32 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

type Payload struct {
	Chunk                uint32   `protobuf:"varint,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	ChunkNum             uint32   `protobuf:"varint,2,opt,name=chunk_num,json=chunkNum,proto3" json:"chunk_num,omitempty"`
	HashKey              string   `protobuf:"bytes,3,opt,name=hash_key,json=hashKey,proto3" json:"hash_key,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{1}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetChunk() uint32 {
	if m != nil {
		return m.Chunk
	}
	return 0
}

func (m *Payload) GetChunkNum() uint32 {
	if m != nil {
		return m.ChunkNum
	}
	return 0
}

func (m *Payload) GetHashKey() string {
	if m != nil {
		return m.HashKey
	}
	return ""
}

func (m *Payload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Request struct {
	Chunk                uint32   `protobuf:"varint,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetChunk() uint32 {
	if m != nil {
		return m.Chunk
	}
	return 0
}

func (m *Request) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Pod struct {
	Sender               string    `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Source               *Location `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination          *Location `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Timestamp            uint64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FlightRadius         uint32    `protobuf:"varint,5,opt,name=flight_radius,json=flightRadius,proto3" json:"flight_radius,omitempty"`
	Priority             uint32    `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Hops                 uint32    `protobuf:"varint,7,opt,name=hops,proto3" json:"hops,omitempty"`
	Payload              *Payload  `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	Request              *Request  `protobuf:"bytes,9,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Pod) Reset()         { *m = Pod{} }
func (m *Pod) String() string { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()    {}
func (*Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{3}
}

func (m *Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pod.Unmarshal(m, b)
}
func (m *Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pod.Marshal(b, m, deterministic)
}
func (m *Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pod.Merge(m, src)
}
func (m *Pod) XXX_Size() int {
	return xxx_messageInfo_Pod.Size(m)
}
func (m *Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_Pod proto.InternalMessageInfo

func (m *Pod) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Pod) GetSource() *Location {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Pod) GetDestination() *Location {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Pod) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Pod) GetFlightRadius() uint32 {
	if m != nil {
		return m.FlightRadius
	}
	return 0
}

func (m *Pod) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Pod) GetHops() uint32 {
	if m != nil {
		return m.Hops
	}
	return 0
}

func (m *Pod) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Pod) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type Data struct {
	Report               []*Report   `protobuf:"bytes,1,rep,name=report,proto3" json:"report,omitempty"`
	Weather              []*Weather  `protobuf:"bytes,2,rep,name=weather,proto3" json:"weather,omitempty"`
	Message              []*Message  `protobuf:"bytes,3,rep,name=message,proto3" json:"message,omitempty"`
	Audio                []*Audio    `protobuf:"bytes,4,rep,name=audio,proto3" json:"audio,omitempty"`
	File                 []*File     `protobuf:"bytes,5,rep,name=file,proto3" json:"file,omitempty"`
	Balloon              *Balloon    `protobuf:"bytes,6,opt,name=balloon,proto3" json:"balloon,omitempty"`
	Plane                *Plane      `protobuf:"bytes,7,opt,name=plane,proto3" json:"plane,omitempty"`
	Vessel               *Vessel     `protobuf:"bytes,8,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vehicle              *Vehicle    `protobuf:"bytes,9,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Spacecraft           *Spacecraft `protobuf:"bytes,10,opt,name=spacecraft,proto3" json:"spacecraft,omitempty"`
	Author               string      `protobuf:"bytes,11,opt,name=author,proto3" json:"author,omitempty"`
	Timestamp            uint64      `protobuf:"varint,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Location             *Location   `protobuf:"bytes,13,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{4}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetReport() []*Report {
	if m != nil {
		return m.Report
	}
	return nil
}

func (m *Data) GetWeather() []*Weather {
	if m != nil {
		return m.Weather
	}
	return nil
}

func (m *Data) GetMessage() []*Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Data) GetAudio() []*Audio {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *Data) GetFile() []*File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Data) GetBalloon() *Balloon {
	if m != nil {
		return m.Balloon
	}
	return nil
}

func (m *Data) GetPlane() *Plane {
	if m != nil {
		return m.Plane
	}
	return nil
}

func (m *Data) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Data) GetVehicle() *Vehicle {
	if m != nil {
		return m.Vehicle
	}
	return nil
}

func (m *Data) GetSpacecraft() *Spacecraft {
	if m != nil {
		return m.Spacecraft
	}
	return nil
}

func (m *Data) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Data) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Data) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Plane struct {
	WindSpeed            uint32   `protobuf:"varint,1,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	GroundSpeed          uint32   `protobuf:"varint,2,opt,name=ground_speed,json=groundSpeed,proto3" json:"ground_speed,omitempty"`
	Squawk               string   `protobuf:"bytes,3,opt,name=squawk,proto3" json:"squawk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plane) Reset()         { *m = Plane{} }
func (m *Plane) String() string { return proto.CompactTextString(m) }
func (*Plane) ProtoMessage()    {}
func (*Plane) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{5}
}

func (m *Plane) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plane.Unmarshal(m, b)
}
func (m *Plane) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plane.Marshal(b, m, deterministic)
}
func (m *Plane) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plane.Merge(m, src)
}
func (m *Plane) XXX_Size() int {
	return xxx_messageInfo_Plane.Size(m)
}
func (m *Plane) XXX_DiscardUnknown() {
	xxx_messageInfo_Plane.DiscardUnknown(m)
}

var xxx_messageInfo_Plane proto.InternalMessageInfo

func (m *Plane) GetWindSpeed() uint32 {
	if m != nil {
		return m.WindSpeed
	}
	return 0
}

func (m *Plane) GetGroundSpeed() uint32 {
	if m != nil {
		return m.GroundSpeed
	}
	return 0
}

func (m *Plane) GetSquawk() string {
	if m != nil {
		return m.Squawk
	}
	return ""
}

type Vessel struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{6}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Vehicle struct {
	Speed                uint32   `protobuf:"varint,1,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vehicle) Reset()         { *m = Vehicle{} }
func (m *Vehicle) String() string { return proto.CompactTextString(m) }
func (*Vehicle) ProtoMessage()    {}
func (*Vehicle) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{7}
}

func (m *Vehicle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vehicle.Unmarshal(m, b)
}
func (m *Vehicle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vehicle.Marshal(b, m, deterministic)
}
func (m *Vehicle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vehicle.Merge(m, src)
}
func (m *Vehicle) XXX_Size() int {
	return xxx_messageInfo_Vehicle.Size(m)
}
func (m *Vehicle) XXX_DiscardUnknown() {
	xxx_messageInfo_Vehicle.DiscardUnknown(m)
}

var xxx_messageInfo_Vehicle proto.InternalMessageInfo

func (m *Vehicle) GetSpeed() uint32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Balloon struct {
	Speed                uint32   `protobuf:"varint,1,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balloon) Reset()         { *m = Balloon{} }
func (m *Balloon) String() string { return proto.CompactTextString(m) }
func (*Balloon) ProtoMessage()    {}
func (*Balloon) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{8}
}

func (m *Balloon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balloon.Unmarshal(m, b)
}
func (m *Balloon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balloon.Marshal(b, m, deterministic)
}
func (m *Balloon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balloon.Merge(m, src)
}
func (m *Balloon) XXX_Size() int {
	return xxx_messageInfo_Balloon.Size(m)
}
func (m *Balloon) XXX_DiscardUnknown() {
	xxx_messageInfo_Balloon.DiscardUnknown(m)
}

var xxx_messageInfo_Balloon proto.InternalMessageInfo

func (m *Balloon) GetSpeed() uint32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Report struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{9}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Report) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Spacecraft struct {
	Name                 uint32   `protobuf:"varint,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Spacecraft) Reset()         { *m = Spacecraft{} }
func (m *Spacecraft) String() string { return proto.CompactTextString(m) }
func (*Spacecraft) ProtoMessage()    {}
func (*Spacecraft) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{10}
}

func (m *Spacecraft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spacecraft.Unmarshal(m, b)
}
func (m *Spacecraft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spacecraft.Marshal(b, m, deterministic)
}
func (m *Spacecraft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spacecraft.Merge(m, src)
}
func (m *Spacecraft) XXX_Size() int {
	return xxx_messageInfo_Spacecraft.Size(m)
}
func (m *Spacecraft) XXX_DiscardUnknown() {
	xxx_messageInfo_Spacecraft.DiscardUnknown(m)
}

var xxx_messageInfo_Spacecraft proto.InternalMessageInfo

func (m *Spacecraft) GetName() uint32 {
	if m != nil {
		return m.Name
	}
	return 0
}

type Weather struct {
	Timestamp            uint64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Temperature          float32  `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity             float32  `protobuf:"fixed32,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Pressure             float32  `protobuf:"fixed32,4,opt,name=pressure,proto3" json:"pressure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weather) Reset()         { *m = Weather{} }
func (m *Weather) String() string { return proto.CompactTextString(m) }
func (*Weather) ProtoMessage()    {}
func (*Weather) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{11}
}

func (m *Weather) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weather.Unmarshal(m, b)
}
func (m *Weather) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weather.Marshal(b, m, deterministic)
}
func (m *Weather) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weather.Merge(m, src)
}
func (m *Weather) XXX_Size() int {
	return xxx_messageInfo_Weather.Size(m)
}
func (m *Weather) XXX_DiscardUnknown() {
	xxx_messageInfo_Weather.DiscardUnknown(m)
}

var xxx_messageInfo_Weather proto.InternalMessageInfo

func (m *Weather) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Weather) GetTemperature() float32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Weather) GetHumidity() float32 {
	if m != nil {
		return m.Humidity
	}
	return 0
}

func (m *Weather) GetPressure() float32 {
	if m != nil {
		return m.Pressure
	}
	return 0
}

type Message struct {
	Receiver             string    `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Body                 string    `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Location             *Location `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{12}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Message) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Audio struct {
	Receiver             string   `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Duration             string   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Blob                 []byte   `protobuf:"bytes,3,opt,name=blob,proto3" json:"blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Audio) Reset()         { *m = Audio{} }
func (m *Audio) String() string { return proto.CompactTextString(m) }
func (*Audio) ProtoMessage()    {}
func (*Audio) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{13}
}

func (m *Audio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Audio.Unmarshal(m, b)
}
func (m *Audio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Audio.Marshal(b, m, deterministic)
}
func (m *Audio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Audio.Merge(m, src)
}
func (m *Audio) XXX_Size() int {
	return xxx_messageInfo_Audio.Size(m)
}
func (m *Audio) XXX_DiscardUnknown() {
	xxx_messageInfo_Audio.DiscardUnknown(m)
}

var xxx_messageInfo_Audio proto.InternalMessageInfo

func (m *Audio) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Audio) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *Audio) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

type File struct {
	Receiver             string   `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Blob                 []byte   `protobuf:"bytes,3,opt,name=blob,proto3" json:"blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_384ce5c482a55d82, []int{14}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "Location")
	proto.RegisterType((*Payload)(nil), "Payload")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Pod)(nil), "Pod")
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*Plane)(nil), "Plane")
	proto.RegisterType((*Vessel)(nil), "Vessel")
	proto.RegisterType((*Vehicle)(nil), "Vehicle")
	proto.RegisterType((*Balloon)(nil), "Balloon")
	proto.RegisterType((*Report)(nil), "Report")
	proto.RegisterType((*Spacecraft)(nil), "Spacecraft")
	proto.RegisterType((*Weather)(nil), "Weather")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Audio)(nil), "Audio")
	proto.RegisterType((*File)(nil), "File")
}

func init() { proto.RegisterFile("aulora.proto", fileDescriptor_384ce5c482a55d82) }

var fileDescriptor_384ce5c482a55d82 = []byte{
	// 766 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xcb, 0x6e, 0xeb, 0x36,
	0x10, 0x85, 0x6d, 0x59, 0x8f, 0xb1, 0xbd, 0x21, 0x8a, 0x42, 0xf7, 0x36, 0xc5, 0xf5, 0x55, 0x51,
	0x20, 0x40, 0x00, 0x2d, 0x12, 0xa0, 0xfb, 0x16, 0x45, 0x17, 0x7d, 0x21, 0x60, 0x80, 0x74, 0xe9,
	0xd0, 0x12, 0x63, 0xa9, 0x96, 0x44, 0x85, 0x8f, 0x04, 0x5e, 0xf6, 0x6f, 0xfa, 0x0b, 0xfd, 0xbb,
	0x82, 0x43, 0x4a, 0xb6, 0x83, 0xa4, 0xdd, 0xf1, 0x9c, 0x33, 0x9c, 0x19, 0x1e, 0xcd, 0xd8, 0xb0,
	0x64, 0xa6, 0x11, 0x92, 0xe5, 0xbd, 0x14, 0x5a, 0x64, 0x0f, 0x10, 0xff, 0x2a, 0x0a, 0xa6, 0x6b,
	0xd1, 0x91, 0x8f, 0x10, 0x37, 0x4c, 0xd7, 0xda, 0x94, 0x3c, 0x9d, 0xac, 0x27, 0x97, 0x2b, 0x3a,
	0x62, 0x72, 0x01, 0x49, 0x23, 0xba, 0x9d, 0x13, 0xa7, 0x28, 0x1e, 0x09, 0x7b, 0x93, 0x35, 0xfe,
	0xe6, 0xcc, 0xdd, 0x1c, 0x70, 0xb6, 0x87, 0xe8, 0x96, 0x1d, 0x1a, 0xc1, 0x4a, 0xf2, 0x05, 0xcc,
	0x8b, 0xca, 0x74, 0x7b, 0x9f, 0xdd, 0x01, 0xf2, 0x15, 0x24, 0x78, 0xd8, 0x74, 0xa6, 0xf5, 0xa9,
	0x63, 0x24, 0x7e, 0x37, 0x2d, 0xf9, 0x00, 0x71, 0xc5, 0x54, 0xb5, 0xd9, 0xf3, 0x03, 0x66, 0x4e,
	0x68, 0x64, 0xf1, 0x2f, 0xfc, 0x40, 0x08, 0x04, 0x25, 0xd3, 0x2c, 0x0d, 0xd6, 0x93, 0xcb, 0x25,
	0xc5, 0x73, 0x76, 0x03, 0x11, 0xe5, 0x4f, 0x86, 0x2b, 0xfd, 0x4e, 0x31, 0x02, 0x81, 0xbd, 0x8f,
	0x75, 0x12, 0x8a, 0xe7, 0xec, 0xef, 0x29, 0xcc, 0x6e, 0x45, 0x49, 0xbe, 0x84, 0x50, 0xf1, 0xae,
	0xe4, 0x12, 0xaf, 0x24, 0xd4, 0x23, 0xf2, 0x19, 0x42, 0x25, 0x8c, 0x2c, 0xdc, 0xc3, 0x17, 0xd7,
	0x49, 0x3e, 0x58, 0x46, 0xbd, 0x40, 0xae, 0x60, 0x51, 0x72, 0xa5, 0xeb, 0x0e, 0x69, 0xec, 0xf4,
	0x2c, 0xee, 0x54, 0xb5, 0x5e, 0xea, 0xba, 0xe5, 0x4a, 0xb3, 0xb6, 0xc7, 0xee, 0x03, 0x7a, 0x24,
	0xc8, 0x37, 0xb0, 0x7a, 0x6c, 0xea, 0x5d, 0xa5, 0x37, 0x92, 0x95, 0xb5, 0x51, 0xe9, 0x1c, 0xfb,
	0x5f, 0x3a, 0x92, 0x22, 0x67, 0x0d, 0xef, 0x65, 0x2d, 0x64, 0xad, 0x0f, 0x69, 0xe8, 0x2c, 0x1b,
	0x30, 0x3e, 0x51, 0xf4, 0x2a, 0x8d, 0x90, 0xc7, 0x33, 0xc9, 0x20, 0xea, 0xdd, 0x47, 0x48, 0x63,
	0xec, 0x2d, 0xce, 0xfd, 0x47, 0xa1, 0x83, 0x60, 0x63, 0xa4, 0xf3, 0x2e, 0x4d, 0x7c, 0x8c, 0xf7,
	0x92, 0x0e, 0x42, 0xf6, 0xcf, 0x0c, 0x82, 0x1f, 0x99, 0x66, 0xe4, 0x13, 0x84, 0x92, 0xf7, 0x42,
	0xea, 0x74, 0xb2, 0x9e, 0x5d, 0x2e, 0xae, 0xa3, 0x9c, 0x22, 0xa4, 0x9e, 0xb6, 0xd9, 0x5e, 0x38,
	0xd3, 0x15, 0x97, 0xe9, 0x14, 0x23, 0xe2, 0xfc, 0x0f, 0x87, 0xe9, 0x20, 0xd8, 0x98, 0x96, 0x2b,
	0xc5, 0x76, 0x76, 0x6a, 0x5c, 0xcc, 0x6f, 0x0e, 0xd3, 0x41, 0x20, 0x17, 0x30, 0x67, 0xa6, 0xac,
	0x45, 0x1a, 0x60, 0x44, 0x98, 0x7f, 0x6f, 0x11, 0x75, 0x24, 0xf9, 0x00, 0xc1, 0x63, 0xdd, 0xf0,
	0x74, 0x8e, 0xe2, 0x3c, 0xff, 0xa9, 0x6e, 0x38, 0x45, 0xca, 0x26, 0xdf, 0xb2, 0xa6, 0x11, 0xa2,
	0x43, 0x87, 0x6c, 0xf2, 0x1f, 0x1c, 0xa6, 0x83, 0x60, 0x93, 0xf7, 0x0d, 0xeb, 0x38, 0x7a, 0x65,
	0x93, 0xdf, 0x5a, 0x44, 0x1d, 0x69, 0xdf, 0xf8, 0xcc, 0x95, 0xe2, 0x8d, 0xf7, 0x2c, 0xca, 0xef,
	0x11, 0x52, 0x4f, 0xdb, 0x12, 0xcf, 0xbc, 0xaa, 0x8b, 0x86, 0x8f, 0x8e, 0xdd, 0x3b, 0x4c, 0x07,
	0x81, 0x5c, 0x01, 0xa8, 0x9e, 0x15, 0xbc, 0x90, 0xec, 0x51, 0xa7, 0x80, 0x61, 0x8b, 0xfc, 0x6e,
	0xa4, 0xe8, 0x89, 0x6c, 0x27, 0x90, 0x19, 0x5d, 0x09, 0x99, 0x2e, 0xdc, 0x04, 0x3a, 0x74, 0x3e,
	0x31, 0xcb, 0xd7, 0x13, 0xf3, 0x2d, 0xc4, 0x8d, 0x1f, 0xb4, 0x74, 0xf5, 0x7a, 0xf2, 0x46, 0x29,
	0x63, 0x30, 0xc7, 0xe7, 0x91, 0xaf, 0x01, 0x5e, 0xea, 0xae, 0xdc, 0xa8, 0x9e, 0xf3, 0xd2, 0xaf,
	0x47, 0x62, 0x99, 0x3b, 0x4b, 0x90, 0xcf, 0xb0, 0xdc, 0x49, 0x61, 0xc6, 0x00, 0xb7, 0x92, 0x0b,
	0xc7, 0xb9, 0x10, 0xbb, 0x29, 0x4f, 0x86, 0xbd, 0xec, 0xfd, 0x4e, 0x7a, 0x94, 0x5d, 0x40, 0xe8,
	0x2c, 0xb2, 0x43, 0xd8, 0xb1, 0x96, 0xfb, 0x4d, 0xc2, 0x73, 0xf6, 0x09, 0x22, 0x6f, 0x8f, 0x5d,
	0xce, 0xd3, 0xea, 0x0e, 0xd8, 0x00, 0xff, 0x89, 0xde, 0x09, 0xf8, 0x0e, 0x42, 0x37, 0x66, 0x24,
	0x85, 0x48, 0x99, 0xed, 0x9f, 0xbc, 0xd0, 0xbe, 0xc4, 0x00, 0x6d, 0xe5, 0xad, 0x28, 0x0f, 0xc3,
	0x86, 0xdb, 0x73, 0xb6, 0x06, 0x38, 0x3a, 0x7e, 0xd6, 0xdb, 0xca, 0xf7, 0xf6, 0xd7, 0x04, 0x22,
	0x3f, 0x9f, 0xe7, 0x6e, 0x4f, 0x5e, 0xbb, 0xbd, 0x86, 0x85, 0xe6, 0x6d, 0xcf, 0x25, 0xd3, 0x46,
	0xba, 0x9f, 0x84, 0x29, 0x3d, 0xa5, 0xec, 0x72, 0x56, 0xa6, 0xad, 0x4b, 0xbb, 0x9c, 0x33, 0x94,
	0x47, 0xec, 0x16, 0x97, 0x2b, 0x65, 0xaf, 0x06, 0x4e, 0x1b, 0x70, 0xf6, 0x00, 0x91, 0x1f, 0x7f,
	0x1b, 0x26, 0x79, 0xc1, 0xeb, 0xe7, 0xf1, 0xc7, 0x68, 0xc4, 0x6f, 0x3d, 0xf0, 0x6c, 0x04, 0x66,
	0xef, 0x8f, 0xc0, 0x1d, 0xcc, 0x71, 0x7d, 0xfe, 0x33, 0xff, 0x47, 0x88, 0x4b, 0x23, 0x5d, 0x2e,
	0x57, 0x63, 0xc4, 0x58, 0xbb, 0x11, 0x5b, 0xac, 0xb1, 0xa4, 0x78, 0xce, 0x7e, 0x86, 0xc0, 0xae,
	0xdd, 0xff, 0xf5, 0x8c, 0x96, 0x4f, 0x8f, 0xe3, 0xf0, 0x56, 0xae, 0x6d, 0x88, 0xff, 0x4a, 0x37,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x4d, 0x51, 0x2a, 0xa5, 0x06, 0x00, 0x00,
}
